server:
  servlet:
    context-path: /wechat/demo
  port: 8081

wechat:
  config:
    #配置一个文字的模板ID 
    template:
      #早安模板
      morningTemplate:
        #模板ID
        templateId: j0SJLFOqcfqHiffZGz0X4b0ZRXh-Jnp_sJ0XtbLFWdY
        #是否关注的用户全发送，ture为是，当值为ture时，sendOpenId 为排除发送对象的微信用户，当值为false为否，sendOpenId为发送对象的微信用户
        allSend: true
        filterOpenIds:
#          - oMkqC6otrLa5greCmThsep_0sYYU
        parameter:
          #这是默认的设置，如果有用户没设置参数，就按此参数
          default:
            #早安话语
            title: Good morning,honey
            #你们的相遇时间
            meetDate: '2018-09-01'
            city: 大同
            #居住地点，高德地图api下载查询 https://lbs.amap.com/api/webservice/download
            cityCode: 0352
            constellation: 摩羯座
          #把‘填写你的需要特定配置的微信用户号’覆盖位微信用户ID，可以对照正确填写好的配置示例，多用户可以按照格式继续添加下去
          填写你的需要特定配置的微信用户号:
            title: 
            meetDate: 
            city: 
            cityCode: 
            constellation: 
      #颜文字模板
      emoticonsTemplate:
        templateId: j0SJLFOqcfqHiffZGz0X4b0ZRXh-Jnp_sJ0XtbLFWdY
        allSend: true
        filterOpenIds:
        parameter:
          default:
            title: 1
#发送者个人信息
personal:
  info:
    constellation: 摩羯座
